### ISSUE TITLE
Basic CLI UI

### ISSUE THREAD

**Issue by cillian64** [cuspaceflight/rockblock_ui#2]
A program, or 3:
- Receive all messages waiting, display them, log them
- Continuously check for new messages and receive+display+log them as they arrive
- Transmit a single message (and maybe receive a waiting message if necessary).

No async or CLI needed, keep it simple.

**Comment by cillian64** [comment]
Frankly once the AT commands are wrapped this could be achieved using an interactive python session...

**Comment by cillian64** [comment]
Adam requests actual CLI of the form:

./rockblock send "my boring message"
./rockblock receive # dumps all waiting rx messages, if any
./rockblock receive_continuous # Continuously checks for messages and dumps as they arrive

**Comment by HarkonenBade** [comment]
hmm, that CLI is a bit awkward given that only one thing can talk to the modem at once. So you would only be able to use one of those commands at any time. Also currently the send command may have the sideeffect of producing some received messages.

**Comment by cillian64** [comment]
Both of those are correct and as intended, so long as nothing too upsetting happens if you try and run more than one command at a time (i.e. open on serial port fails, program exits, is fine ).  And just have the send command dump any received messages.  This fits fine with the actual workflow, if not the neatness of the interface.

Instead of receive_continuous just have "./rockblock receive" be a continuous receive thing.  Possibly consider a way to avoid adam accidentally hitting Ctrl+C during a buffer exchange or at an upsetting time -- maybe intercept SIGwhatever and exit after dumping any receives in progress?
