### ISSUE TITLE
Ensure adam does not have to mentally insert carriage returns.

### ISSUE THREAD

**Issue by cillian64** [cuspaceflight/rockblock_ui#4]
The rockblock "incorrectly" handles carriage returns in messages. Adam is deeply unhappy about having to mentally parse these line breaks.  Ensure he no longer has to do this.

**Comment by cillian64** [comment]
Basically this should be fine, the rockblock only sends '\n', but one would expect (or at least screen does) "\r\n" on a serial device.

**Comment by HarkonenBade** [comment]
Yeah this is understandable as a carriage return is the message terminating char for sends, and thus presumably should never appear in a message body. I'm not sure how my current code plays out with line breaks in messages, we should have a test at some point.

**Comment by cillian64** [comment]
Have clarified with @adamgreig, I had misunderstoof, there were no linebreaks in messages (let's assume that is invalid and/or impossible), the problem was the rockblock itself sending \n instead of \r\n which made screen unhappy.  So we are of course sidestepping this issue.
